# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_we', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentVerifyTicketLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Status', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Create Time', verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Update Time', verbose_name='updated_at')),
                ('component_appid', models.CharField(blank=True, db_index=True, help_text='Component APPID', max_length=32, null=True, verbose_name='component_appid')),
                ('component_secret', models.CharField(blank=True, help_text='Component Secret', max_length=32, null=True, verbose_name='component_secret')),
                ('component_verify_ticket', jsonfield.fields.JSONField(blank=True, help_text='Component Verify Ticket', null=True, verbose_name='component_verify_ticket')),
            ],
            options={
                'verbose_name': 'componentverifyticketloginfo',
                'verbose_name_plural': 'componentverifyticketloginfo',
            },
        ),
    ]
